#%RAML 1.0
title: Test
/v1/start:
  description: This will trigger the test execution within the container
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              message: string
            example: |
              {
                "message": "started"
              }
/v1/summary:
  description: At any point, accessing this api will return the summary of testcases executed till that point
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              total: number
              passed: number
              failed: number
              skipped: number
            example: |
              {
                "total": 10,
                "passed": 7,
                "failed": 1,
                "skipped": 2
              }
/v1/end:
  description: This will end the testcase execution within the container and it will return to an idle state
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              message: string
            example: |
              {
                "message": "ended"
              }
/v1/live:
  description: This api will return all the test cases that were executed from the last time this api was accessed. Please note that this is not cumulative and returns on the delta of testcases that were executed after the last call to this api.
  get:
    responses:
      200:
        body:
          application/json:
            type: array
            example: |
              [
                {
                  "name": "testcase1",
                  "suitename": "suite1",
                  "status": "passed"
                },
                {
                  "name": "testcase2",
                  "suitename": "suite1",
                  "status": "failed"
                },
                {
                  "name": "testcase3",
                  "suitename": "suite2",
                  "status": "skipped"
                }
              ]
/v1/status:
  description: This api will report the status of the test container any given point in time. It can one of the following values "running", "stopped"
  get:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              status: string
            example: |
              {
                "status": "running"
              }
              