#hana db settings
spring:
  flyway:
    enabled: true
    locations: classpath:sql/migration
    table: SCHEMA_VERSION
    validate-on-migrate: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      default_schema: "SAMPLEAPPDEV"
    properties:
      hibernate:
        dialect: org.hibernate.dialect.HANAColumnStoreDialect
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    url: jdbc:sap://hana.service.${DOMAIN_NAME}:39044?encrypt=true
    username: "SAMPLEAPPDEV"
    driverClassName: com.sap.db.jdbc.Driver
    platform: ""
    password: "Hanauser1"