server:
  port: 8080
  name: localhost
  greeting: greeting-service
  orchestrator: ${COBALT_ORCHESTRATOR:Orchestrator}
  proxy:
    isProduction: false
    url: https://sdk.split.io/
    proxyHost: https-proxy.service
    proxyPort: 3128
    nonProxyHosts: localhost|*.service
sample:
    groupa:
        param1: value1base
        param2: value2base
    higherparam: valuehigherbase

spring:
  profiles:
    active: hsql
  datasource.hikari: #HikariCP connection Pool
    pool-name: greeting-service
    connection-timeout: 60000  # Default: 30000 (30 seconds)
    maximum-pool-size: 10  #Default: 10
